[workspace]
members = [
    "termist",
    "termist_terminal",
    "termist_config",
    "termist_config_derive",
]
resolver = "2"

# [profile.release]
# lto = "thin"
# debug = 1
# incremental = false
